# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2024.8.30-hbcca054_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2024a-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h5eee18b_6.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.6.2-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-73.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlicommon-1.0.9-h5eee18b_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h5eee18b_3.conda
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.18-h36c2ea0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.3.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.15-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.14-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.6-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46306.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlidec-1.0.9-h5eee18b_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlienc-1.0.9-h5eee18b_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcups-2.4.2-h2d74bed_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20230828-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libllvm14-14.0.6-hdb19cb5_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.10.4-hfdd30dd_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre2-10.42-hebb0a14_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.14-h39e8969_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.5-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-bin-1.0.9-h5eee18b_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.20.1-h143b758_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang13-14.0.6-default_he11475f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libglib-2.78.4-hdc74915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxkbcommon-1.0.1-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46344.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.45.3-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-h5eee18b_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/cyrus-sasl-2.1.28-h52b45da_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.14.1-h4c34cd2_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-tools-2.78.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang-14.0.6-default_hc6dbbc7_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.17-hdbd6064_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.4.0-h3ad879b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.11.9-h955ad1f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blinker-1.6.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.1.7-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/colorama-0.4.6-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/debugpy-1.6.7-py311h6a678d5_0.conda
https://conda.anaconda.org/conda-forge/noarch/decorator-5.1.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dill-0.3.8-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/exceptiongroup-1.2.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/executing-2.0.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.78.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/greenlet-3.0.1-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/iniconfig-1.1.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/isort-5.9.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/itsdangerous-2.2.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lazy-object-proxy-1.10.0-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.3-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/mccabe-0.7.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py311h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mypy_extensions-1.0.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mysql-5.7.24-h721c034_2.conda
https://conda.anaconda.org/conda-forge/noarch/nest-asyncio-1.6.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.2-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/parso-0.8.4-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/pickleshare-0.7.5-py_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pillow-10.3.0-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/platformdirs-3.10.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pluggy-1.0.0-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ply-3.11-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py311h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/ptyprocess-0.7.0-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pure_eval-0.2.3-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pycodestyle-2.11.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyflakes-3.2.0-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/pygments-2.18.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.0.9-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt5-sip-12.13.0-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.11-2_cp311.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2024.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-25.1.2-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ruff-0.3.5-py311hab49468_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-69.5.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tomlkit-0.11.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.3.3-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tqdm-4.66.5-py311h92b7b1e_0.conda
https://conda.anaconda.org/conda-forge/noarch/traitlets-5.14.3-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.11.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/unicodedata2-15.1.0-py311h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.2.13-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.43.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.14.1-py311h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.20.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/astroid-2.14.2-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/asttokens-2.4.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/black-24.3.0-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/comm-0.2.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/flake8-7.0.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fonttools-4.51.0-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.1-h5eee18b_1.conda
https://conda.anaconda.org/conda-forge/noarch/importlib-metadata-8.4.0-pyha770c72_0.conda
https://conda.anaconda.org/conda-forge/noarch/jedi-0.19.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.4-py311h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/jupyter_core-5.7.2-py311h38be061_0.conda
https://conda.anaconda.org/conda-forge/noarch/matplotlib-inline-0.1.7-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.26.4-py311hf175353_0.conda
https://conda.anaconda.org/conda-forge/noarch/pexpect-4.9.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/prompt-toolkit-3.0.47-pyha770c72_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytest-7.4.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.9.0post0-py311h06a4308_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-6.7.12-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing-extensions-4.11.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-3.0.3-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/flask-3.0.3-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.1-h6a678d5_1.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-8.4.0-hd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mypy-1.8.0-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pylint-2.16.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlalchemy-2.0.25-py311h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/stack_data-0.6.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/ipython-8.27.0-pyh707e725_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-8.6.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-main-5.15.2-h53bd1ea_10.conda
https://conda.anaconda.org/conda-forge/noarch/ipykernel-6.29.5-pyh3099207_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.15.10-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.3.7-py311hf4808d0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.2.0-py311hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.8.4-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.8.4-py311ha02d727_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.8-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.4-py311hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.26.4-py311h08b1b3b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.8.7-py311h65dcdc2_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-2.2.1-py311ha02d727_0.conda
astroid==3.3.8
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
babel==2.16.0
black @ file:///croot/black_1712698501521/work
blinker @ file:///croot/blinker_1696539051175/work
Bottleneck @ file:///croot/bottleneck_1707864210935/work
certifi==2024.12.14
charset-normalizer==3.4.0
click @ file:///croot/click_1698129812380/work
colorama @ file:///work/ci_py311/colorama_1676827038675/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
contourpy @ file:///croot/contourpy_1700583582875/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
dill @ file:///croot/dill_1715094664823/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
flake8 @ file:///croot/flake8_1708965256870/work
Flask @ file:///croot/flask_1716545870149/work
fonttools @ file:///croot/fonttools_1713551344105/work
ghp-import==2.1.0
greenlet @ file:///croot/greenlet_1702059959679/work
idna==3.10
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1724187233579/work
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1725050136642/work
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
itsdangerous @ file:///croot/itsdangerous_1716533337253/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2 @ file:///croot/jinja2_1716993405101/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1716472197302/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1710257359434/work
kiwisolver @ file:///work/ci_py311/kiwisolver_1676827230232/work
lazy-object-proxy @ file:///croot/lazy-object-proxy_1712908712693/work
Markdown==3.7
MarkupSafe @ file:///croot/markupsafe_1704205993651/work
matplotlib @ file:///croot/matplotlib-suite_1713336378214/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
mccabe @ file:///opt/conda/conda-bld/mccabe_1644221741721/work
mergedeep==1.3.4
mkdocs==1.6.1
mkdocs-autolinks-plugin==0.7.1
mkdocs-callouts==1.15.0
mkdocs-content-tabs==1.0.5
mkdocs-ezlinks-plugin==0.1.14
mkdocs-get-deps==0.2.0
mkdocs-material==9.5.49
mkdocs-material-extensions==1.3.1
mkdocs-obsidian-bridge==1.1.1
mkdocs-obsidian-interactive-graph-plugin==0.3.0
mkdocs-obsidian-support-plugin==1.4.1
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
mypy @ file:///croot/mypy-split_1708366513367/work
mypy-extensions @ file:///croot/mypy_extensions_1695130926492/work
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
numexpr @ file:///croot/numexpr_1696515281613/work
numpy @ file:///croot/numpy_and_numpy_base_1708638617955/work/dist/numpy-1.26.4-cp311-cp311-linux_x86_64.whl#sha256=5f96f274d410a1682519282ae769c877d32fdbf171aa8badec7bf5e1d3a1748a
obsidian-media==2.0.0
overrides==7.7.0
packaging @ file:///croot/packaging_1710807400464/work
paginate==0.5.7
pandas @ file:///croot/pandas_1709590491089/work/dist/pandas-2.2.1-cp311-cp311-linux_x86_64.whl#sha256=0a2793a31a0135a35735e1431d453a06186a3a7c607d9b441d9bd5f0fe4ded31
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
pathspec==0.12.1
patool==2.3.0
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow @ file:///croot/pillow_1714398848491/work
platformdirs @ file:///croot/platformdirs_1692205439124/work
pluggy @ file:///work/ci_py311/pluggy_1676822818071/work
ply==3.11
prompt_toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1718047967974/work
psutil @ file:///work/ci_py311_2/psutil_1679337388738/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure_eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1721585709575/work
pycodestyle @ file:///croot/pycodestyle_1701821051884/work
pyflakes @ file:///croot/pyflakes_1708962956225/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
pygtrie==2.5.0
pylint==3.3.3
pymdown-extensions==10.12
pyparsing @ file:///work/ci_py311/pyparsing_1677811559502/work
PyQt5==5.15.10
PyQt5-sip @ file:///croot/pyqt-split_1698769088074/work/pyqt_sip
pytest @ file:///croot/pytest_1690474690005/work
python-dateutil @ file:///croot/python-dateutil_1716495738603/work
pytz @ file:///croot/pytz_1713974312559/work
PyYAML==6.0.2
pyyaml_env_tag==0.1
pyzmq @ file:///croot/pyzmq_1705605076900/work
regex==2024.11.6
requests==2.32.3
ruff @ file:///croot/ruff_1713370963143/work
sip @ file:///croot/sip_1698675935381/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
SQLAlchemy @ file:///croot/sqlalchemy_1705089115293/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
tomlkit @ file:///work/ci_py311/tomlkit_1676823218885/work
tornado @ file:///croot/tornado_1696936946304/work
tqdm @ file:///croot/tqdm_1724853939799/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
typing_extensions @ file:///croot/typing_extensions_1715268824938/work
tzdata @ file:///croot/python-tzdata_1690578112552/work
unicodedata2 @ file:///croot/unicodedata2_1713212950228/work
urllib3==2.3.0
watchdog==6.0.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
Werkzeug @ file:///croot/werkzeug_1716533313107/work
wrapt @ file:///work/ci_py311/wrapt_1676827586170/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1724730934107/work
