site_name: whispers-from-the-ash  # Replace with your vault name
theme: readthedocs               
plugins:
  - search
  - obsidian-support:
      use_shields: true   # Display backlinks and other metadata
      home_page: index    # Specify your home page (optional)