site_name: whispers-from-the-ash  
theme: readthedocs
nav:
  - Home: home.md
  - About: about.md
  - index: index.md
plugins:
  - search
  - obsidian-support:
      # use_shields: true   # Display backlinks and other metadata
      # home_page: index    # Specify your home page (optional)