name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with your Python version

    - name: Create conda environment
      run: |
        conda create -n my_env --file requirements.txt
        conda activate my_env

    - name: Install pip dependencies
      run: pip install -r requirements.txt

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site